### ISSUE TITLE
Proposal to upgrade site implementations.

### ISSUE THREAD

**Issue by huacnlee** [pest-parser/site#32]
1. [ ] Switch CodeMirror to [Monaco Editor](https://microsoft.github.io/monaco-editor).
    Monaco Editor have a better API for code editing, for example diagnostics.
3. [x] Integration [Tailwind CSS](https://tailwindcss.com/) for better CSS development and add mobile support.
4. [x] Add [Vite](https://vitejs.dev) as the front-end build tool.
5. [x] JavaScript to TypeScript and Use React for build view.
6. [ ] Add a link on top right navigation bar (Before the `Book`), named `Play`. 
 
If we agree that, I can do it.

**Comment by LeoDog896** [comment]
(We did discuss parcel vs vite in #30, as well as not using tailwind).

- I agree with "Add a link on top right navigation bar (Before the Book), named Play."
- I do not agree with a switch from codemirror to monaco editor - monaco editor is generally a _lot_ more heavier, and since we don't have a language server that we can use with advanced diagnostics support, I think it would be better to hold off and use codemirror until we can offer more complex features to justify the usage of monaco.

**Comment by tomtau** [comment]
Yes, I'd second that and prefer keeping the site simpler/lighter. For the more advanced stuff, it's perhaps better to do it in the VSCode extension, and prepare a devcontainer / gitpod file, so that one can easily spin up the full fledged editor in GitHub Codespaces or Gitpod.io ?
